# -*- coding: utf-8 -*-
"""Kaggle (Students Performance in Exams).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2IXLYtySnDF3hwEw8UK6XattQQZjW9f

## **Experiment 02**                               Date:02/02/2026

## **Exploratory Data Analysis (EDA) on Student Performance Dataset using Python**

## Introduction / Theory

## Exploratory Data Analysis (EDA) is a crucial step in data analysis that helps us understand the structure, patterns, and relationships within a dataset before applying any machine learning or statistical models.

## In this experiment, EDA is performed on a Student Performance Dataset that contains students’ scores in Math, Reading, and Writing, along with demographic attributes such as gender and lunch type.

## EDA uses:

## Statistical summaries (mean, correlation)

## Graphical techniques (histogram, bar chart, boxplot, scatter plot, heatmap)

## The objective is to identify trends, distributions, correlations, and performance differences among students.

## Q1. Uploading CSV File and Viewing Dataset Theory

A CSV (Comma Separated Values) file is a common format used to store tabular data. Loading the dataset into a DataFrame allows structured analysis and easy manipulation of data.

Explanation

The dataset is uploaded into the working environment.

It is loaded into a Pandas DataFrame.

Displaying the first five records helps verify:

Correct data loading

Column names

Initial data structure
"""

from google.colab import files
files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

df = pd.read_csv("StudentsPerformance.csv")
df.head()

"""##Q2. Histogram of Math Scores Theory

A histogram is a graphical representation of data distribution. It groups numerical values into ranges (bins) and shows how frequently values occur.

Explanation

The histogram of Math Scores shows how student performance is distributed.

It helps identify:

Most common score ranges

Whether scores are skewed or normally distributed

Overall performance trend in mathematics
"""

# Histogram
plt.figure(figsize=(9, 6))
sns.histplot(df["math score"], bins=25, kde=True)
plt.title("Histogram of Math Scores")
plt.xlabel("Math Score")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df["math score"], bins=15, kde=True)
plt.title("Histogram of Math Scores")
plt.xlabel("Math Score")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(25, 11))
sns.histplot(df["math score"], bins=25, kde=True)
plt.title("Histogram of Math Scores")
plt.xlabel("Math Score")
plt.ylabel("Frequency")
plt.show()

"""## Q3. Average Scores Grouped by Gender Theory

Grouping data allows comparison between categories. Calculating average scores by gender helps identify performance differences.

Explanation

Scores are grouped into male and female categories.

Mean values of Math, Reading, and Writing scores are calculated.

This analysis highlights subject-wise gender performance trends.
"""

# Bar graph
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("StudentsPerformance.csv")

# Calculate average scores by gender
avg_scores = df.groupby("gender")[["math score", "reading score", "writing score"]].mean()
avg_scores = avg_scores.reset_index().melt(
    id_vars="gender",
    var_name="Subject",
    value_name="Average Score"
)

# Bar chart
plt.figure(figsize=(8, 5))
sns.barplot(x="gender", y="Average Score", hue="Subject", data=avg_scores)
plt.title("Average Exam Scores by Gender")
plt.xlabel("Gender")
plt.ylabel("Average Score")
plt.show()

avg_scores = df.groupby("gender")[["math score","reading score","writing score"]].mean()

avg_scores.plot(kind="bar", figsize=(8,6))
plt.title("Average Scores by Gender")
plt.ylabel("Average Score")
plt.xticks(rotation=0)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("StudentsPerformance.csv")

# Calculate average scores by gender
avg_scores = df.groupby("gender")[["math score", "reading score", "writing score"]].mean()
avg_scores = avg_scores.reset_index().melt(
    id_vars="gender",
    var_name="Subject",
    value_name="Average Score"
)

# Bar chart
plt.figure(figsize=(18, 9))
sns.barplot(x="gender", y="Average Score", hue="Subject", data=avg_scores)
plt.title("Average Exam Scores by Gender")
plt.xlabel("Gender")
plt.ylabel("Average Score")
plt.show()

"""## Q4. Bar Chart using Pandas Plot Method Theory

Pandas provides built-in plotting methods for quick visualization without complex configurations.

Explanation

The bar chart shows average subject scores by gender.

It confirms trends observed in previous analysis.

Pandas plotting is efficient for rapid exploratory analysis.
"""

# Boxplot
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("StudentsPerformance.csv")

# Boxplot of scores
plt.figure(figsize=(8, 5))
sns.boxplot(data=df[["math score", "reading score", "writing score"]])
plt.title("Boxplot of Exam Score Distribution")
plt.ylabel("Score")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(data=df[["math score","reading score","writing score"]])
plt.title("Score Distribution (Boxplot)")
plt.ylabel("Score")
plt.show()

plt.figure(figsize=(28,15))
sns.boxplot(data=df[["math score","reading score","writing score"]])
plt.title("Score Distribution (Boxplot)")
plt.ylabel("Score")
plt.show()

"""## Q5. Scatter Plot between Reading and Writing Scores Theory

Scatter plots visualize the relationship between two numerical variables.

Explanation

Each point represents a student.

Points forming a diagonal pattern indicate strong correlation.

Shows how reading performance relates to writing ability.
"""

# Scatter Plot
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("StudentsPerformance.csv")

# Scatter plot
plt.figure(figsize=(8, 5))
sns.scatterplot(
    x="reading score",
    y="writing score",
    data=df,
    alpha=0.6
)
plt.title("Scatter Plot of Reading vs Writing Scores")
plt.xlabel("Reading Score")
plt.ylabel("Writing Score")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(
    x="reading score",
    y="writing score",
    data=df,
    hue="gender"
)
plt.title("Reading vs Writing Scores")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("StudentsPerformance.csv")

# Scatter plot
plt.figure(figsize=(5, 2))
sns.scatterplot(
    x="reading score",
    y="writing score",
    data=df,
    alpha=0.6
)
plt.title("Scatter Plot of Reading vs Writing Scores")
plt.xlabel("Reading Score")
plt.ylabel("Writing Score")
plt.show()

plt.figure(figsize=(35,25))
sns.scatterplot(
    x="reading score",
    y="writing score",
    data=df,
    hue="gender"
)
plt.title("Reading vs Writing Scores")
plt.show()

"""## Q 06. Heatmap of Correlation Matrix Theory

A heatmap represents correlation values using colors.

Explanation

Darker colors represent stronger relationships.

Makes correlation interpretation easier and faster.

Confirms strong interdependence between subjects.
"""

# Heatmap
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("StudentsPerformance.csv")

# Correlation matrix
corr = df[["math score", "reading score", "writing score"]].corr()

# Heatmap
plt.figure(figsize=(7, 5))
sns.heatmap(corr, annot=True, cmap="coolwarm", linewidths=0.5)
plt.title("Correlation Heatmap of Exam Scores")
plt.show()

corr = df[["math score","reading score","writing score"]].corr()

plt.figure(figsize=(6,4))
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

corr = df[["math score","reading score","writing score"]].corr()

plt.figure(figsize=(16,8))
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

"""## Q 07. Correlation Heatmap for Standard Lunch Students Theory

External factors such as nutrition may affect academic performance.

Explanation

Data is filtered for students with standard lunch.

Correlation heatmap shows stronger score relationships.

Indicates better consistency in performance for students with proper nutrition.
"""

standard_lunch_corr = df[df["lunch"] == "standard"][
    ["math score","reading score","writing score"]
].corr()

plt.figure(figsize=(6,4))
sns.heatmap(standard_lunch_corr, annot=True, cmap="cubehelix")
plt.title("Correlation (Standard Lunch Students)")
plt.show()

"""## Q 08. Correlation Heatmap for Female Students Theory

Analyzing subsets helps identify group-specific patterns.

Explanation

Heatmap focuses only on female students.

Correlations are compared with overall data.

Helps understand gender-based academic trends.
"""

female_corr = df[df["gender"] == "female"][
    ["math score","reading score","writing score"]
].corr()

plt.figure(figsize=(6,4))
sns.heatmap(female_corr, annot=True, cmap="magma")
plt.title("Correlation Heatmap (Female Students)")
plt.show()

"""## **Result**

The Exploratory Data Analysis (EDA) performed on the Student Performance Dataset successfully revealed important patterns and relationships among students’ academic scores.

The dataset was loaded and explored successfully, confirming correct structure and attributes.

Histogram analysis showed that Math scores have a wider distribution, indicating greater variation in student performance compared to Reading and Writing.

Gender-wise analysis revealed that female students generally scored higher in Reading and Writing, while Math scores were comparatively balanced.

Bar charts clearly highlighted average score differences between male and female students.

Boxplots indicated that most scores lie within a normal range, with a few outliers representing exceptionally high or low performances.

Scatter plots showed a strong positive relationship between Reading and Writing scores.

Correlation matrices and heatmaps confirmed that Reading and Writing scores are highly correlated, followed by a moderate correlation with Math.

Students with standard lunch showed stronger and more consistent score relationships.

Female-only correlation analysis showed trends similar to overall data, with slightly stronger correlations in language subjects.

## **Conclusion**

This experiment demonstrated that Exploratory Data Analysis is an effective technique for understanding student academic performance before applying advanced statistical or machine learning methods.

Through visualizations such as histograms, bar charts, boxplots, scatter plots, and heatmaps, meaningful insights were obtained regarding score distribution, gender differences, subject relationships, and the influence of lunch type on performance.

The analysis concludes that:

Reading and Writing skills are closely related, indicating that improvement in one can positively impact the other.

Gender and nutritional factors play a significant role in student performance.

Visual EDA techniques simplify complex data and support data-driven decision making.

Overall, EDA provides a strong foundation for further academic performance analysis and predictive modeling.
"""